"""Add encryption and message metadata

Revision ID: 253eacc4fae4
Revises: ddee800ce7ea
Create Date: 2026-07-22 16:13:09.399389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253eacc4fae4'
down_revision: Union[str, Sequence[str], None] = 'ddee800ce7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("encrypted",sa.Boolean(),nullable=False,server_default=sa.false(),),)
    op.add_column('messages', sa.Column('encryption_algorithm', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.add_column("messages", sa.Column("edited",sa.Boolean(), nullable=False,server_default=sa.false(),),)
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column("messages", sa.Column("deleted_for_everyone",sa.Boolean(),nullable=False,server_default=sa.false(),),)
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.alter_column(
    "messages",
    "encrypted",
    server_default=None,
    )

    op.alter_column(
        "messages",
        "edited",
        server_default=None,
    )

    op.alter_column(
        "messages",
        "deleted_for_everyone",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'message_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'deleted_for_everyone')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'edited')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'encryption_algorithm')
    op.drop_column('messages', 'encrypted')
    # ### end Alembic commands ###
