"""add message delivery receipts

Revision ID: 41d7ece6fc3f
Revises: 8ced45c8e9dd
Create Date: 2026-07-19 13:12:23.429391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d7ece6fc3f'
down_revision: Union[str, Sequence[str], None] = '8ced45c8e9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
