"""create users table

Revision ID: 68c01cfa89da
Revises: 
Create Date: 2026-07-17 23:35:09.299315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c01cfa89da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary UUID identifier.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email used for OTP authentication.'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique public username.'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='User display name.'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Optional user biography.'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Profile picture URL.'),
    sa.Column('public_key', sa.Text(), nullable=True, comment='Public encryption key used for E2EE.'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the account is active.'),
    sa.Column('online_status', sa.String(length=20), nullable=False, comment='Current user presence status.'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Last active timestamp.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
