"""add otp table

Revision ID: c18cfa5bd45f
Revises: aeca978596ae
Create Date: 2026-07-17 23:53:19.719536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18cfa5bd45f'
down_revision: Union[str, Sequence[str], None] = 'aeca978596ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address receiving the OTP.'),
    sa.Column('otp_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the OTP.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='OTP expiration timestamp.'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='Number of failed verification attempts.'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='Whether this OTP has already been used.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
