"""add otp indexes

Revision ID: fc6b2d57d076
Revises: c18cfa5bd45f
Create Date: 2026-07-18 14:14:12.605805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6b2d57d076'
down_revision: Union[str, Sequence[str], None] = 'c18cfa5bd45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_otp_email_expires', 'otp_codes', ['email', 'expires_at'], unique=False)
    op.alter_column('users', 'public_key',
               existing_type=sa.TEXT(),
               comment='Public encryption key used for end-to-end encryption.',
               existing_comment='Public encryption key used for E2EE.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=sa.TEXT(),
               comment='Public encryption key used for E2EE.',
               existing_comment='Public encryption key used for end-to-end encryption.',
               existing_nullable=True)
    op.drop_index('ix_otp_email_expires', table_name='otp_codes')
    # ### end Alembic commands ###
